### ISSUE TITLE
MVPI

### ISSUE THREAD

**Issue by wendellmva** [wendellmva/ngx-menu#1]
# Tasks 

## Example:

- [ ] [mmenu-light](https://mmenujs.com/mmenu-light/)
- [ ] [mmenu-light code](https://github.com/FrDH/mmenu-light/blob/master/src/core/index.ts)

## Workspace:

- [ ] [setup nx workspace](https://nx.dev/angular/tutorial/01-create-application)
- [ ] [setup npm publishable library with nx](https://nx.dev/angular/tutorial/08-create-libs)
- [ ] add ngx-menu component
- [ ] [setup demo app with storybook](https://nx.dev/angular/plugins/storybook/overview)
- [ ] [add layout with css grid](https://learncssgrid.com/)
- [ ] setup reactive states:
  - [ ] ngx-menu--open
  - [ ] ngx-menu--hidden
  - [ ] ngx-menu--minimized
- [ ] add angular animation on state change

## Button and Drawer:

- [ ] [add close button](https://codepen.io/colinhx/pen/WMRPeo)
- [ ] [close drawer](https://stackoverflow.com/questions/38975808/adding-an-angular-animation-to-a-host-element)

## Menu items:

- [ ] managing menu items
- [ ] [dragging and dropping menu items](https://stackblitz.com/edit/angular-sortable)
- [ ] searching for menuitems
